### ISSUE TITLE
Update Text File Paths

### ISSUE THREAD

**Issue by lealgamb** [vocatwk/CodeU-Nemo#108]
I'm thinking of placing the text files in `webapp` since it's where the favicon and `index.jsp` are located.

**Comment by yebrahim** [comment]
Those are web resources though, unlike the data file.
Do any of the [suggestions here](https://stackoverflow.com/questions/40361154/how-to-read-text-file-on-base-level-of-java-maven-project) work?

**Comment by lealgamb** [comment]
Will try them out! Sorry for rushing the PR.

**Comment by lealgamb** [comment]
I've been trying different approaches but I keep getting a FileNotFoundException. I moved the text file to `src/main/resources`.

**Comment by lealgamb** [comment]
Here's some of the code that handles opening the file

https://github.com/vocatwk/CodeU-Nemo/blob/3ca6e8436c4abac224ad38f71d59622bfca64ac7/src/main/java/codeu/model/data/NemoBot.java#L60-L63

**Comment by yebrahim** [comment]
Maybe all you need is:
```
NemoBot nemoBot = new NemoBot(classLoader.getResource("NemoBot.txt").getFile());
```

**Comment by lealgamb** [comment]
Still doesn't work. It gets the correct path but can't open the file.

**Comment by yebrahim** [comment]
Locally or on appengine?

**Comment by lealgamb** [comment]
Locally. Haven't tried on appengine.

**Comment by lealgamb** [comment]
I got it to work just now. I'll push the changes for review. Still have to try appengine.
