### ISSUE TITLE
Multiple Instances of NemoBot

### ISSUE THREAD

**Issue by lealgamb** [vocatwk/CodeU-Nemo#113]
I noticed that each time `ServerStartupListener` there's a new `NemoBot` instance. This results in multiple `NemoBot` users. I tried changing how `BotController` adds bots to the `UserStore`. 

```
private void registerBotAsUser(Bot bot) {
  User botUser = userStore.getUser(bot.getName());
  if (botUser == null) {
    userStore.addUser((User)bot);
  }
  else {
    userStore.updateUser(botUser);
  }
}
```
However, this then breaks the code when displaying messages.
In `chat.jsp`: `String author = UserStore.getInstance().getUser(message.getAuthorId()).getName();`

I think this can be solved by setting a static id, and to follow this maybe we can also set a static creation time.

**Comment by yebrahim** [comment]
Not sure I understand. So does the `contextInitialized` method get called multiple times?

**Comment by lealgamb** [comment]
I believe so. I'm pretty sure that's the only place where any bot is created. For example, this is on the live site: 
![image](https://user-images.githubusercontent.com/31300741/42976575-1e35a09c-8b77-11e8-90d1-a707b7c50228.png)

The same thing happened locally. For each time I restarted the devserver, a new bot was registered as a user.

**Comment by jasminechau2** [comment]
could you get rid of .getInstance()?

**Comment by yebrahim** [comment]
Ah, yea that makes sense. I thought it fires multiple times during the lifetime of the server, but yea. We totally overlooked this case.

I can't think of a good solution for this without changing the way we store users, to isolate storage of bots in a separate Datastore entity.

**Comment by yebrahim** [comment]
A more brittle way is to add an `isBot` field set to true on all Bot instances, then use that along with the bot's name (mentionkey) to identify bots. Not as clean as storing bot separately, but should work.

**Comment by lealgamb** [comment]
Would `isBot` belong to `User`? Then on startup, the following happens:

```
//load all users
boolean foundNemoBot = false; // repeat for other bots
for (User user : users) {
  if (isBot) {
    if (user.getName().equals("NemoBot") {
      NemoBot nemoBot = botController.getBot("@NemoBot"); 
      foundNemoBot = true;
    }
    else if (user.getName().equals("ConversationStatBot") {
      // same as above
    }
  }
}

if (!foundNemoBot) {
  NemoBot nemoBot = new NemoBot();
}
// repeat for other bots
```

**Comment by lealgamb** [comment]
It might just be better to create the new Datastore entity.

**Comment by yebrahim** [comment]
What I had in mind was that the register bot method would first search the database to make sure a bot doesn’t exist with the same mention key. 

I agree creating a separate entity is much cleaner though.

**Comment by yebrahim** [comment]
Do you know if it’s possible to save just the bot’s class name in the controller, so that we create a new bot instance when answering messages, and we never save it as a user?

**Comment by lealgamb** [comment]
I found [this](https://stackoverflow.com/questions/37302774/map-with-class-as-key) SO question that talks about that.  

The way that messages are displayed relies on `UserStore` so I think we have to save bots as a uses.

**Comment by lealgamb** [comment]
Can making all bots singletons help us? That way we'll only be working with the same instance over the lifetime of the server.
