### ISSUE TITLE
Disable Usernames with the word "Bot" (Register & Login)

### ISSUE THREAD

**Issue by lealgamb** [vocatwk/CodeU-Nemo#114]
Should we disable usernames that contain "bot"? This can users distinguish bots from actual users.

Also, I was able to log in as NemoBot. I know that this is because I know the password, but disabling usernames with the word bot when logging in can help security.

**Comment by yebrahim** [comment]
I don't think we should worry about logging in as bots, we can just set their password to some long random string. I'm not opposed to adding code to forbid bots from logging in, but I'd rather that effort go somewhere more lacking.

Disabling usernames containing "bot" can be tricky. Logs of strings can contain "bot" and seem like reasonable usernames. First names can even contain that, so I'd stay clear from forcing more restrictions on usernames.

**Comment by lealgamb** [comment]
Thanks for this feedback. I think this issue is basically obsolete now thanks to the UUID idea you suggested in PR #115.
