### ISSUE TITLE
Activity Feed Design

### ISSUE THREAD

**Issue by lealgamb** [vocatwk/CodeU-Nemo#24]
Hey guys, here are my initial thoughts for the activity feed design.

- Display events chronologically (most recent -> oldest)

- Make all usernames and conversation titles links

- Eventually group similar events:

- i.e. "UserA sent 10 messages in ConversationA"

For the last point I'm not sure if something like "10 users joined" will work with the ordering. But changing the ordering based on 30/60 minute intervals might work, such as "10 users joined in the last hour".

**Comment by yebrahim** [comment]
One more thing is finding a way to only show new messages since last login?

**Comment by lealgamb** [comment]
I'll definitely try to implement these ideas. For the MVP is it okay to keep the current implementation though?

**Comment by yebrahim** [comment]
Yes of course. The MVP is all about getting the bare minimum working fully. These are just extensions/explorations to give us ideas what we can do next.

**Comment by yebrahim** [comment]
@vocatwk @jasminechau2 I encourage you guys to do something similar, to kick off a discussion on possible extensions to your features. These can serve as a good starting point for exploring topics for the open project.

**Comment by vocatwk** [comment]
I've been thinking about those too. I will create an issue with a list of things i've been thinking about soon.

**Comment by lealgamb** [comment]
Thanks for the ideas.

**Comment by yebrahim** [comment]
Looks like this can be closed? If we still want to work on another part of it, let's separate it out into its own issue so we can track the work more closely.
