### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by lealgamb** [vocatwk/CodeU-Nemo#29]
Hey guys, some of the other teams made one main jsp file for the navigation bar to make it easier to update and remove redundancy. I think this would be beneficial for us.

They shared this link: https://stackoverflow.com/questions/1296235/jsp-tricks-to-make-templating-easier

And here are the steps for another approach they took:
1. Create a new file ```navbar.jsp``` on view folder

1. Copy all the ```<nav></nav>``` segment of code into ```navbar.jsp```

1. In for example ```conversation.jsp``` change the nav code to: ```<%@include file="navbar.jsp" %>```

**Comment by vocatwk** [comment]
I think that's a great idea!

**Comment by yebrahim** [comment]
I really like this! Maintaining separate copies of the same thing for each page of the site is of course not a great idea.
@lealgamb do you have an estimate how much work this is?

**Comment by lealgamb** [comment]
Turned out to be pretty simple.
