### ISSUE TITLE
Profile pages - prototype

### ISSUE THREAD

**Issue by vocatwk** [vocatwk/CodeU-Nemo#7]

**Comment by yebrahim** [comment]
@vocatwk is this done? You can close the issue if it is, since you're tracking tests in a separate issue.
One neat trick to do this automatically is to include this string in your PR's description: "Fixes #7". As soon as the PR is merged, the issue will be closed automatically! :)

**Comment by vocatwk** [comment]
Oh cool, will definitely make sure of that. I was just waiting to close it until after the PR with the fixes and test gets merged.
