### ISSUE TITLE
Set Up Bot Framework

### ISSUE THREAD

**Issue by lealgamb** [vocatwk/CodeU-Nemo#88]
- [x] Make a `Bot` interface

- [x] Rework the current `Bot` class

- [x] Make a `BotController` class

- [x] Update `ChatServlet` accordingly

**Comment by yebrahim** [comment]
I'd switch the order of the last two. We should probably get the new controller done first, then make the chat servlet use it.

**Comment by lealgamb** [comment]
I'm having trouble figuring out where to save the controller. It makes sense to have it in the `controller` folder. However, it also kind of functions as a store model in the sense that it registers and gets bots.

**Comment by yebrahim** [comment]
It doesn't really store bots right? It's just a central controller where bots are registered and retrieved, so it's a runtime-only concept. Bots are created as classes, also in controller, then registered using the bot controller during our app initialization, and the code to do that will probably be static.

**Comment by lealgamb** [comment]
That cleared things up, thanks!

**Comment by lealgamb** [comment]
Now that `BotController` is set up, where is the most appropriate place to register a bot? I'm leaning towards registering it within each bot class.

**Comment by yebrahim** [comment]
Seems like a startup kind of operation for me. How about in `ServerStartupListener`?
