### ISSUE TITLE
Profile pages - tests

### ISSUE THREAD

**Issue by vocatwk** [vocatwk/CodeU-Nemo#9]
Write tests for the prototype.

**Comment by lealgamb** [comment]
Not sure if this is where I should leave this but I noticed that when you click on the navigation tab "hello user" and you're already on a profile page (whether its yours or not) it redirects you to the homepage.

**Comment by vocatwk** [comment]
Oh, you're right.  I'll make sure to fix that in another PR.

**Comment by yebrahim** [comment]
Nice catch @lealgamb.

@all, please keep an eye on the behavior of the app, and file a new issue for any problem the see, however small.
